sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt -r Brightphone/blogs 'GIT_NAME="Brightphone" GIT_EMAIL="zbrihgtz@163.com" GH_TOKEN=661fe74c316c62a02c15d3ca2fe2dcd43ba6c88f'
env:
  global:
    secure: "csMElW7OxcBtyfk/Axie/rUPaP3avmMZ0LzrLyiqIoRivxkhjPbwzT1p/9oZgF2YbkeLvJQvpo6mtMfLSEmXgk7NGUks1WmgGCK78u3rhdG1drEqqHr3CKHN5igZpw1InZlawq8k06y4tLiNtAZ8USod053jLb/CG7md81u3claWB1KS38rrmNw+h/PnVb9OIXrYiMDLjtHK5FXkLgeXncS0IOo/a7Xry2r8mh+uqQPtGZ4psEjvhFBqZeUjp78PHH65peAGGOBC5hd5p+XlfGmkAaLrR2mVD83mm8vgsiDqhSher7JDAXoZkc6xCRj59ZR98GnGzrVFyNEcQO9Iz+1+4ZlTBeF6bX6VBDITVmg9PB0ZNR0PhkX/ThUQDQKOxwJ6sWvYSx0Qg/qbnemo+QHdKzg4j1d1XTGMNCFY+kf9Kd5nKzayuoMBKmfArXrWA3YOWlaVSYjkc82mCxXsl9T5/Zj19yiD+WnBYLNqyEDDIqpgeV5Ch7vm04uV++wqjF/4mpWtXUt+6n7U/nSE2UePyFo25/YYS1ZtOp/UwWUBohwddSsrpDb8Pkit1FXmYB1n8mKeRW8GuieOv8FF1JYTgAJRoLxv8HsA/O5pxTBa8o1iojxRMTNlxm3Xndh7bdecwDzCHIhqWCWx/NgvN1CxGgQkqktBJ3GCci4n27o="
  only:
    - master
